from .empresa import EmpresaSerializer
from .setor import SetorSerializer
from .permissao import PermissaoSerializer
from .grupo import GrupoSerializer
from .usuario import UsuarioSerializer
from .equipamento import EquipamentoSerializer
from .ordem_servico import OrdemServicoSerializer
from .categoria_documento import CategoriaDocumentoSerializer
from .documento_equipamento import DocumentoEquipamentoSerializer
from .anexo_os import AnexoOSSerializer
from .analise_llm import AnaliseLLMSerializer
from .historico_os import HistoricoOSSerializer