# Generated by Django 6.0.4 on 2026-05-21 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_empresa', '0001_initial'),
        ('app_setor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_equipamento', models.CharField(max_length=255)),
                ('tipo_equipamento', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=100)),
                ('id_interno', models.IntegerField()),
                ('qr_code_token', models.CharField(max_length=255, unique=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='equipamentos/fotos/')),
                ('manual_tecnico', models.FileField(blank=True, null=True, upload_to='equipamentos/manuais/')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='equipamentos', to='app_empresa.empresa')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='equipamentos', to='app_setor.setor')),
            ],
        ),
    ]
