# Generated by Django 6.0.4 on 2026-05-21 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnexoOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caminho_arquivo', models.FileField(upload_to='anexos_os/')),
                ('nome_arquivo', models.CharField(max_length=255)),
            ],
        ),
    ]
