# Generated by Django 6.0.4 on 2026-04-09 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_equipamento', models.CharField(max_length=255)),
                ('tipo_equipamento', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=100)),
                ('id_interno', models.IntegerField()),
                ('qr_code_token', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Permissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_permissao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caminho_arquivo', models.FileField(upload_to='documentos_equipamentos/')),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='documentos', to='pandora.categoriadocumento')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='pandora.equipamento')),
            ],
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('urgencia', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('descricao_problema', models.TextField()),
                ('data_fechamento', models.DateTimeField(blank=True, null=True)),
                ('descricao_solucao', models.TextField(blank=True, null=True)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ordens_servico', to='pandora.equipamento')),
            ],
        ),
        migrations.CreateModel(
            name='AnexoOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caminho_arquivo', models.FileField(upload_to='anexos_os/')),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='pandora.ordemservico')),
            ],
        ),
        migrations.CreateModel(
            name='AnaliseLLM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_consulta', models.DateTimeField(auto_now_add=True)),
                ('pergunta_prompt', models.TextField()),
                ('resposta_ia', models.TextField()),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analises_ia', to='pandora.ordemservico')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_grupo', models.CharField(max_length=255)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='grupos', to='pandora.empresa')),
                ('permissoes', models.ManyToManyField(related_name='grupos', to='pandora.permissao')),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_setor', models.CharField(max_length=255)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='setores', to='pandora.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='equipamento',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='equipamentos', to='pandora.setor'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_usuario', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha_hash', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='usuarios', to='pandora.empresa')),
                ('grupos', models.ManyToManyField(related_name='usuarios', to='pandora.grupo')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='usuarios', to='pandora.setor')),
            ],
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='usuario_abertura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='os_abertas', to='pandora.usuario'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='usuario_tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='os_atendidas', to='pandora.usuario'),
        ),
        migrations.CreateModel(
            name='HistoricoOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_modificacao', models.DateTimeField(auto_now_add=True)),
                ('campo_alterado', models.CharField(max_length=255)),
                ('valor_anterior', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_novo', models.CharField(blank=True, max_length=255, null=True)),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='pandora.ordemservico')),
                ('usuario_modificacao', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='modificacoes', to='pandora.usuario')),
            ],
        ),
    ]
