# Generated by Django 6.0.4 on 2026-04-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandora', '0002_fix_usuario_auth_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='equipamentos/fotos/'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='manual_tecnico',
            field=models.FileField(blank=True, null=True, upload_to='equipamentos/manuais/'),
        ),
    ]
