# Generated by Django 6.0.4 on 2026-04-25 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandora', '0003_equipamento_foto_equipamento_manual_tecnico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoequipamento',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='documentos', to='pandora.categoriadocumento'),
        ),
    ]
