# Generated by Django 6.0.4 on 2026-04-26 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandora', '0004_alter_documentoequipamento_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico', to='pandora.equipamento'),
        ),
    ]
