# Generated by Django 6.0.4 on 2026-04-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandora', '0005_alter_ordemservico_equipamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='foto_problema',
            field=models.ImageField(blank=True, null=True, upload_to='os/problemas/'),
        ),
    ]
