# Generated by Django 6.0.4 on 2026-05-03 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandora', '0006_ordemservico_foto_problema'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicoos',
            old_name='valor_anterior',
            new_name='comentario',
        ),
        migrations.RemoveField(
            model_name='historicoos',
            name='campo_alterado',
        ),
        migrations.RemoveField(
            model_name='historicoos',
            name='valor_novo',
        ),
        migrations.AddField(
            model_name='equipamento',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='equipamentos', to='pandora.empresa'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ordens_servico', to='pandora.empresa'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='usuarios', to='pandora.empresa'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='grupos',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='pandora.grupo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='usuarios', to='pandora.setor'),
        ),
    ]
