# Generated by Django 6.0.4 on 2026-05-03 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandora', '0007_rename_valor_anterior_historicoos_comentario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisellm',
            name='usuario_consulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='analises_llm', to=settings.AUTH_USER_MODEL),
        ),
    ]
