# Generated by Django 6.0.4 on 2026-05-21 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_modificacao', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.CharField(blank=True, max_length=255, null=True)),
                ('campo_alterado', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_anterior', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_novo', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Historico de OS',
                'verbose_name_plural': 'Historicos de OS',
                'ordering': ['-data_modificacao'],
            },
        ),
    ]
