# Generated by Django 6.0.4 on 2026-05-21 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnaliseLLM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_consulta', models.DateTimeField(auto_now_add=True)),
                ('pergunta_prompt', models.TextField()),
                ('resposta_ia', models.TextField()),
            ],
        ),
    ]
