# Generated by Django 6.0.4 on 2026-05-21 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_analise', '0001_initial'),
        ('app_os', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisellm',
            name='os',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analises_ia', to='app_os.ordemservico'),
        ),
    ]
