# Generated by Django 6.0.4 on 2026-05-21 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_categoria', '0001_initial'),
        ('app_equipamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caminho_arquivo', models.FileField(upload_to='documentos_equipamentos/')),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='documentos', to='app_categoria.categoriadocumento')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='app_equipamento.equipamento')),
            ],
        ),
    ]
