# Generated by Django 6.0.4 on 2026-05-21 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_empresa', '0001_initial'),
        ('app_equipamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('urgencia', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('descricao_problema', models.TextField()),
                ('foto_problema', models.ImageField(blank=True, null=True, upload_to='os/problemas/')),
                ('data_fechamento', models.DateTimeField(blank=True, null=True)),
                ('descricao_solucao', models.TextField(blank=True, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ordens_servico', to='app_empresa.empresa')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico', to='app_equipamento.equipamento')),
            ],
        ),
    ]
