# Generated by Django 6.0.4 on 2026-05-21 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_os', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='usuario_abertura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='os_abertas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='usuario_tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='os_atendidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
