# Generated by Django 6.0.3 on 2026-04-06 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('id_interno', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_arquivo', models.CharField(max_length=50)),
                ('caminho_url', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_perfil', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_equipamento', models.CharField(max_length=255)),
                ('tipo_equipamento', models.CharField(max_length=100)),
                ('criticidade', models.IntegerField()),
                ('qr_code', models.CharField(max_length=255, unique=True)),
                ('status_ativo', models.BooleanField(default=True)),
                ('id_interno', models.IntegerField(blank=True, null=True)),
                ('manual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.manual')),
            ],
        ),
        migrations.CreateModel(
            name='Ordem_servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('urgencia', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipamento')),
            ],
        ),
        migrations.CreateModel(
            name='Anexo_OS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_anexo', models.CharField(max_length=50)),
                ('caminho_url', models.URLField(max_length=500)),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='core.ordem_servico')),
            ],
        ),
        migrations.CreateModel(
            name='Analise_LLM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomalia_detectada', models.TextField()),
                ('causa_raiz', models.TextField()),
                ('acao_sugerida', models.TextField()),
                ('os', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.ordem_servico')),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_setor', models.CharField(max_length=100)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setores', to='core.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='equipamento',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.setor'),
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_usuario', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha_hash', models.CharField(max_length=255)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.perfil')),
                ('setor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.setor')),
            ],
        ),
        migrations.AddField(
            model_name='ordem_servico',
            name='usuario_abertura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='os_abertas', to='core.usuarios'),
        ),
        migrations.AddField(
            model_name='ordem_servico',
            name='usuario_tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='os_atendidas', to='core.usuarios'),
        ),
    ]
