# Generated by Django 6.0.3 on 2026-04-07 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_empresa_id_interno'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='core.empresa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.setor'),
        ),
    ]
