# Generated by Django 6.0.3 on 2026-04-07 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usuarios_ativo_usuarios_empresa_alter_usuarios_setor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='manual',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='manual',
            name='equipamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='manuais', to='core.equipamento'),
            preserve_default=False,
        ),
    ]
